language: node_js
node_js:
  - "6"
  - "10"
notifications:
  email:
    - services@wikimedia.org
services:
  - mysql
before_install:
  - mysql -uroot -e "CREATE DATABASE \`test_db\`;"
  - mysql -uroot -e "CREATE USER 'mysql'@\`%\` IDENTIFIED BY 'mysql';"
  - mysql -uroot -e "GRANT ALL PRIVILEGES ON \`test_db\`.* TO 'mysql'@\`%\`;"
